apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mec-chart.fullname" . }}
  labels:
    {{- include "mec-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mec-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        # Basic settings
        MAX_CLIENTS: {{ .Values.configs.MAX_CLIENTS }}
        # User - plane mode or Control - plane more
        UPLANE_CPLANE: {{ .Values.configs.UPLANE_CPLANE }}
        # IP and port settings
        UE_NETMASK: {{ .Values.configs.UE_NETMASK }}
        UE_SUBNET: {{ .Values.configs.UE_SUBNET }}
        # OAI
        CORE_IP: {{ .Values.configs.CORE_IP }}
        CORE_SEND_PORT: {{ .Values.configs.CORE_SEND_PORT }}
        ENB_IP: {{ .Values.configs.ENB_IP }}
        MEC_IP: {{ .Values.configs.MEC_IP }}
        MEC_LISTEN_PORT: {{ .Values.configs.MEC_LISTEN_PORT }}
        MEC_SEND_PORT: {{ .Values.configs.MEC_SEND_PORT }}
        SERVICE_SUBNET: {{ .Values.configs.SERVICE_SUBNET }}
    {{- end }}
      labels:
        {{- include "mec-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mec-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          # The ConfigMap we want to use
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          env:
          - name: "MAX_CLIENTS"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.MAX_CLIENTS
          - name: "UPLANE_CPLANE"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.UPLANE_CPLANE
          - name: "UE_NETMASK"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.UE_NETMASK
          - name: "UE_SUBNET"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.UE_SUBNET
          - name: "CORE_IP"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.CORE_IP
          - name: "CORE_SEND_PORT"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.CORE_SEND_PORT
          - name: "ENB_IP"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.ENB_IP
          - name: "MEC_IP"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.MEC_IP
          - name: "MEC_LISTEN_PORT"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.MEC_LISTEN_PORT
          - name: "MEC_SEND_PORT"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.MEC_SEND_PORT
          - name: "SERVICE_SUBNET"
            valueFrom:
              fieldRef:
                fieldPath: spec.template.metadata.annotations.SERVICE_SUBNET
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
